
window.console=window.console||{log:function(){}};var Ta=window.Ta||{};Ta.$=function(id){return document.getElementById(id);};Ta.module={};Ta.empty={el:document.createElement('span'),fn:function(){},isEmpty:function(obj){for(var p in obj){return false;}
return true;}};Ta.util={template:function(json,tmpl){for(var p in json){tmpl=tmpl.replace(new RegExp('<%='+p+'%>','g'),json[p]);}
return tmpl;},loadJS:function(source,fn,type){var node=document.createElement('script'),script=document.getElementsByTagName('script')[0];node.type='text/javascript';if(type){node.text=source;}
else{node.src=source;node.onload=node.onerror=node.onreadystatechange=function(){/loaded|complete|undefined/.test(node.readyState)&&function(){node.onload=node.onerror=node.onreadystatechange=null;node.parentNode.removeChild(node);node=undefined;fn();}();};}
script.parentNode.insertBefore(node,script);type&&setTimeout(function(){node.parentNode.removeChild(node);node=undefined;},200);},html:function(elem,str){if(/<html>|<head>|<body>/i.test(str)){elem.innerHTML='template error';}
else if(/script/i.test(str))
{var htmlPool,scriptPool=[],filePool=[],regFile=/<script[^>]*src=[\'\"](.*?)[\'\"][^>]*>(.*?)<\/script>/gi,regCode=/<script[^>]*>([\s\S]*?)<\/script>/gi;str=str.replace(regFile,function(match,file){filePool.push(file);return''});str=str.replace(regCode,function(match,code){scriptPool.push(code);return''});htmlPool=str;var HDL=function(){HDL.count--;if(HDL.count<1){each(scriptPool,function(code){Ta.util.loadJS(code,null,1);});}};HDL.count=filePool.length;var each=function(arr,fn){for(var i=0;i<arr.length;i++)
{fn(arr[i]);}};elem.innerHTML=htmlPool;if(filePool.length>0){each(filePool,function(src){Ta.util.loadJS(src,HDL);});}
else{each(scriptPool,function(code){Ta.util.loadJS(code,null,1);});}}
else{elem.innerHTML=str;}},addEvt:function(elem,type,hdl){var callback=function(evt){var evt=window.event||evt,target=evt.srcElement||evt.target;hdl(evt,target);};window.addEventListener&&elem.addEventListener(type,callback,false)||window.attachEvent&&elem.attachEvent('on'+type,callback);},contains:function(p,c){return p.contains?p!=c&&p.contains(c):!!(p.compareDocumentPosition(c)&16);},sort:function(arr,index,order){return arr.sort(function(a,b){var ret=b[index]-a[index];return(isNaN(ret)?b[index].localeCompare(a[index]):ret)*(order||1);});},openWindow:function(url,nav){nav=nav||Ta.hash.get(0);url=$.browser.mozilla?encodeURIComponent(encodeURIComponent(encodeURIComponent(url))):encodeURIComponent(url);url='/summary/index?sId='+Ta.module.site.sid+'#!'+nav+Ta.hash.interval+Ta.module.site.sid+Ta.hash.interval+url;window.open(url);},assembleParam:function(obj){var p=[];obj&&function(){for(var c in obj){p.push(c+'='+obj[c]);}}();return p.join('&');},showWindows:function(content,title,callback,btnType,extra,type,winSize){var opts={type:type||1,title:title||'提示信息',content:content||'',btnType:btnType||1,winSize:winSize||1,extra:extra};if(btnType&&isNaN(parseInt(btnType))){opts.buttons={text1:btnType,text2:''};opts.btnType=6;}
extra&&extra['type']&&(extra['type']=='tips'||extra['type']=='report_tips')&&(opts.hideCloseIcon=true);var dialog=new Ta.Dialog(opts,callback);return dialog;},loading:function(ele,extra){var def={left:0,right:0,top:0,bottom:0};def=$.extend(true,def,extra);var div=document.createElement('div');div.style.height='24px';div.style.width='24px';if($('#'+ele).width()>24){div.style.marginLeft=($('#'+ele).width()/2-12)+'px';}
if($('#'+ele).height()>24){div.style.marginTop=($('#'+ele).height()/2-12)+'px';}
def.bottom>0&&(div.style.marginBottom=def.bottom+'px');def.top>0&&(div.style.marginTop=def.top+'px');div.innerHTML='<i class="i_loading"></i>';$('#'+ele).html(div);},mask:{prefix:'mask4',show:function(id,extra){var that=this;var style=function(){if($('#'+id).length>0){return{width:$('#'+id).width(),height:$('#'+id).height(),offset:$('#'+id).offset(),padding:$('#'+id).css('padding')};}
return null;}();if(style){$('<div id="'+that.prefix+id+'"><i class="i_loading"></i>&nbsp;数据加载中...</div>').css({height:style.height+'px',left:style.offset.left+'px',position:'absolute',padding:style.padding,'padding-top':'80px',top:style.offset.top+'px','text-align':'center',width:style.width+'px',background:'#FFF','opacity':0.4,'z-index':50}).appendTo('body');}},clear:function(id){if(id&&$('#'+this.prefix+id).length>0){$('#'+this.prefix+id).remove();}
else{$('div[id^="'+this.prefix+'"]').each(function(){$(this).remove();});}}},browser:{_ua:navigator.userAgent.toLowerCase(),parser:function(){var ua=this._ua;var Sys={};if(window.ActiveXObject)
Sys.ie=ua.match(/msie ([\d.]+)/)[1]
else if(document.getBoxObjectFor)
Sys.firefox=ua.match(/firefox\/([\d.]+)/)[1]
else if(window.MessageEvent&&!document.getBoxObjectFor)
Sys.chrome=ua.match(/chrome\/([\d.]+)/)[1]
else if(window.opera)
Sys.opera=ua.match(/opera.([\d.]+)/)[1]
else if(window.openDatabase)
Sys.safari=ua.match(/version\/([\d.]+)/)[1];return Sys;}},showMessage:function(content,detail,title,type,btnType,extra){var opts={type:type,title:title||'温馨提示',content:content,detail:detail,btnType:btnType,extra:extra||{top:250}};if(!opts.extra['top']){opts.extra['top']=250;}
var dialog=new Ta.Dialog(opts);},showItemTips:function(tipsContent,offsetElement,extra){var TIPS_TIMEOUT={};var TIPS_SHOW_TIMEOUT={};var index=1;return function(){tipsId=(extra&&typeof(extra['id'])!='undefined')?extra['id']:('f_win_tips'+index++);tipsTop=(extra&&typeof(extra['top'])!='undefined')?extra['top']:-20;tipsLeft=(extra&&typeof(extra['left'])!='undefined')?extra['left']:-67;autoClose=(extra&&typeof(extra['autoClose'])!='undefined')?extra['autoClose']:true;if(TIPS_TIMEOUT[tipsId]){clearTimeout(TIPS_TIMEOUT[tipsId]);}
pos=$(offsetElement).offset();cla=(extra&&typeof(extra['cla'])!='undefined')?extra['cla']:'i_orderu';tipsQ='<div id="'+tipsId+'" class="tips"> <i class="'+cla+'"></i> '
+' <p>'+tipsContent+'</p>'
+' </div>';if(!$('#'+tipsId)[0]){$(tipsQ).appendTo('body');}
tipsTop=-27;tipsLeft=-12;tipsStyle={'top':(pos.top-$('#'+tipsId).height()+tipsTop)+'px','left':(pos.left+tipsLeft)+'px','display':'none'};tipsTop=8;tipsLeft=-12;tipsStyle={'top':(pos.top+$(offsetElement).height()+tipsTop)+'px','left':(pos.left+tipsLeft)+'px','display':'none'};tipsTop=-10;tipsLeft=10;tipsStyle1={'top':(pos.top+tipsTop)+'px','left':(pos.left+$(offsetElement).width()+tipsLeft)+'px','display':'none'};tipsTop=-10;tipsLeft=-30;tipsStyle1={'top':(pos.top+tipsTop)+'px','left':(pos.left-$('#'+tipsId).width()+tipsLeft)+'px','display':'none'};$('#'+tipsId).css(tipsStyle);$('#'+tipsId).mouseover(function(){clearTimeout(TIPS_TIMEOUT[tipsId]);});$('#'+tipsId).mouseout(function(){clearTimeout(TIPS_TIMEOUT[tipsId]);TIPS_TIMEOUT[tipsId]=setTimeout(function(){$('#'+tipsId).fadeOut();},200);});$(offsetElement).mouseout(function(){if(TIPS_SHOW_TIMEOUT[tipsId]){clearTimeout(TIPS_SHOW_TIMEOUT[tipsId]);}
if(TIPS_TIMEOUT[tipsId]){clearTimeout(TIPS_TIMEOUT[tipsId]);}
var id=$(this).attr('id');TIPS_TIMEOUT[tipsId]=setTimeout(function(){$('#'+tipsId).fadeOut();},200);});$('div.tips').fadeOut();TIPS_SHOW_TIMEOUT[tipsId]=setTimeout(function(){$('#'+tipsId).fadeIn();},600);}();},popup:function(btn,ctn,wrap,css){css=css||'pop';var ITEMS_TIMEOUT=null;function hidePop(){$('#'+ctn).removeClass(css);}
function showPop(){$('#'+ctn).addClass(css);}
function isPopShow(){return $('#'+ctn).attr('class')==css;}
$("#"+btn).click(function(){Ta.util.pageHotClick(btn);isPopShow()?hidePop():showPop();}).mouseover(function(){clearTimeout(ITEMS_TIMEOUT);}).mouseout(function(){ITEMS_TIMEOUT=setTimeout(hidePop,200);});$('#'+wrap).mouseover(function(){clearTimeout(ITEMS_TIMEOUT);}).mouseout(function(){ITEMS_TIMEOUT=setTimeout(hidePop,200);});},loadAjaxData:function(data){this.pageHotClick('LOAD');var ROW_NUM=7;var TABLE_WIDTH=762;var TABLE_ROW_WIDTH=130;var LOGIN_MSG='对不起,您尚未登录, 请登录后再进行操作.';var ajaxReg=/<ajax id="(.*?)">([^\x00]+?)<\/ajax>/ig;var ajaxAlertReg=/<ajaxAlert>([^\x00]+?)<\/ajaxAlert>/ig;if(data.match(ajaxAlertReg)){ajaxTipsMsg=data.replace(ajaxAlertReg,function($0,$1){if($1==LOGIN_MSG){Ta.Login.open(window.location.href);return;}
Ta.util.showMessage($1,'','',4,3);return'';});return true;}
if(!data.match(ajaxReg)){var mod=Ta.$('module');this.html(mod,data);return;}
ajaxMsg=data.replace(ajaxReg,function($0,$1,$2){var objectReg=/(embed|object)$/ig;var scriptReg=/<script(.*?)>([^\x00]+?)<\/script>/ig;var obj=$('#'+$1);if(1>obj.length){return'';}
if(objectReg.exec(obj.attr('nodeName'))){var script=($2).match(scriptReg);if(script[0]){obj.append(script[0]);}
return'';}
obj.empty().append($2).show();if($2.indexOf(LOGIN_MSG)!=-1){Ta.Login.open(window.location.href);return;}
return'';});},sendHotClick:function(tag){var fn=Tcss.pgvSendClick||pgvSendClick;fn({hottag:tag});},pageHotClick:function(name){var pageTitle='PAGE';if(Ta.Page&&Ta.Page.fullTitle){pageTitle=Ta.Page.fullTitle.split('-').join('.');}
name='TAV2.'+pageTitle+'.'+name;var fn=Tcss.pgvSendClick||pgvSendClick;fn({hottag:name});}};Ta.bind=function(attr){var model=function(arg){for(var p in attr){this[p]=attr[p];}
this.events=this.events||{};this.initialize&&this.initialize(arg);}
model.prototype.get=function(name){return this[name]||'';};model.prototype.set=function(attr){var pool={},hdl;for(var p in attr){var arr=p.split('.'),len=arr.length,first=arr[0],last=arr[len-1],hash=this,i=-1;while(++i<len-1){hash=hash[arr[i]]=hash[arr[i]]||{};}
hash[last]!==attr[p]&&(hash[last]=attr[p],pool[first]=this[first]);}
for(var p in pool){(hdl=this.events[p])&&this[hdl](pool[p]);}};model.prototype.save=function(){};model.prototype.fetch=function(){};return model;};Ta.Task=function(options){for(var p in options){this[p]=options[p];}
Ta.Task.pool[options.type][options.name]=setTimeout(options.task,options.delay);}
Ta.Task.kill=function(name){var pool=Ta.Task.pool[0];if(name){clearTimeout(pool[name]);}
else{for(var p in pool){clearTimeout(pool[p]);delete pool[p];}}};Ta.Task.killAll=function(){this.kill();var pool=Ta.Task.pool[1];for(var p in pool){clearTimeout(pool[p]);delete pool[p];}}
Ta.Task.pool=[{},{}];Ta.cache=function(){var pool={},size=0,MAX=50;return{get:function(key){var json,value='';if(json=pool[key]){if(new Date()-json['last-modified']<json['cache-control']){json['weight']++;value=json['value'];}
else{this.gc(key);}}
return value;},set:function(key,value,time){if(size<MAX){size++;pool[key]={'last-modified':+new Date(),'cache-control':time,'value':value,'weight':0};}
else{this.gc();}},gc:function(key){var del=function(key){delete pool[key];size--;};if(key){del(key);}
else{var arr=[],now=+new Date();for(var p in pool){if(now-pool[p]['last-modified']<pool[p]['cache-control']){arr.push(p+'|'+pool[p]['weight']);}
else{this.gc(p);}}
arr.sort(function(a,b){return b.split('|')[1]-a.split('|')[1];}).slice(25);for(var i=0,l=arr.length;i<l;i++){del(arr[i].split('|')[0]);}}}}}();Ta.loadTemplate=function(url,fn){var cache;$.ajax({url:url,success:function(data){fn(data);Ta.cache.set(url,data,300000);}});return true;};Ta.ajax=function(options){options.url=options.url+(~options.url.indexOf('?')?'&':'?')+'sId='+Ta.module.site.sid+'&random='+(+new Date()),$.ajax(options);};Ta.RealTime=function(options){new(Ta.bind({data:options.data,events:{data:'render'},render:options.render,initialize:function(){var that=this,min=options.min||5000,max=options.max||30000,delay=min;void function(){fn=arguments.callee;Ta.ajax({url:options.url,dataType:options.dataType,data:options.params,success:function(data){data==that.get('data')?(delay<max&&(delay+=1000)):(delay=min,that.set({data:data}));new Ta.Task({name:'dashboard_heartbeat',delay:delay,task:fn,type:options.type||0});}});}()}}))();this.id=+new Date();};Ta.heart=function(opts){new Ta.RealTime({url:opts.url,min:4000,max:30000,type:0,dataType:'json',params:opts.params,render:function(){opts.fn(arguments[0]);}})};Ta.hash={interval:'&&',disabled:false,_:function(){var hash=window.location.hash.substr(2);return hash?hash.split(this.interval):[];},get:function(index){return(this._()[index]||'');},set:function(index,value){var arr=this._();arr[index]=value;window.location.hash='#!'+arr.join(this.interval);},clearHash:function(index){Ta.hash.get(index)&&(Ta.hash.disabled=false,Ta.hash.set(index,''),Ta.hash.disabled=true);}};Ta.Menu=function(json,hdl){this.mainId='';this.subId='';this.last={};this.hdl=hdl;this.history=[];this.subMenu={};var that=this,parent={main:Ta.$(json.main.menu_id)||Ta.empty.el,sub:Ta.$(json.sub.menu_id)||Ta.empty.el},subHash={},subTT={};var create=function(mod,init){var tmpl=json[mod].tmpl_id?Ta.$(json[mod].tmpl_id).innerHTML:'<li menu="<%=index%>"><a href="javascript:;"><%=menu%></a></li>',wrap=parent[mod],data=json[mod].data,util=Ta.util;if(mod=='main'){var arr=[];for(var p in data){(!data[p].split('|')[1])&&arr.push(util.template({index:mod+'-'+p,menu:data[p]},tmpl));}
wrap.innerHTML='<ul>'+arr.join('')+'</ul>';}
else{for(var p in data){var arr=[],icon=1;subTT[p]={};for(var pp in data[p]){var st=Ta.empty.isEmpty(data[p][pp])?'style="display:none;"':'';arr.push('<h3 '+st+'><i class="i_icon'+icon+'">&nbsp;</i>'+pp+'</h3><ul '+st+'>');for(var i in data[p][pp]){var ssTitle=data[p][pp][i].split('|');(!ssTitle[1])&&arr.push(util.template({index:mod+'-'+i,menu:data[p][pp][i]},tmpl));subTT[p][i]=data[p][pp][i];}
arr.push('</ul>');icon++;}
subHash[p]=arr.join('');}}
init&&util.addEvt(wrap,'click',function(evt,target){var tmp,arr,main,sub;(tmp=target.parentNode.getAttribute("menu"))&&function(){arr=tmp.split('-');arr[0]=='main'?(main=arr[1],sub=undefined):(main=undefined,sub=arr[1]);Ta.hash.clearHash(2);$('html,body').animate({scrollTop:'0px'},1000);that.change(main,sub,null,true);}();});},hashChange=function(){if(Ta.hash.disabled){return;}
var hash=Ta.hash.get(0),arr,len=that.history.length;hash&&hash!=that.history[len-1]&&(arr=hash.split('-'))&&that.change(arr[0],arr[1]);},cls=function(mod,active){var children=parent[mod].getElementsByTagName('li'),child,index;for(var l=children.length,i=l-1;0<=i;i--){child=children[i];(child.nodeType==1)&&(index=child.getAttribute('menu'))&&function(){child.className=index.split('-')[1]==active?'current':'';}();}},init=function(){Ta.Task&&Ta.Task.kill();create('main',1);create('sub',1);!Ta.hash.get(0)&&Ta.hash.set(0,'0-0');hashChange();window.onhashchange=hashChange;};this.change=function(main,sub,fn,enableHotClick){json.main.data[main]&&(this.mainId=main,this.subId=this.last[this.mainId]||0,parent.sub.innerHTML=subHash[main],parent.sub.style.display=subHash[main]?'':'none',cls('main',main),cls('sub',this.subId));(!isNaN(parseInt(sub)))&&(this.subId=this.last[this.mainId]=subTT[this.mainId][sub]?sub:0,cls('sub',this.subId));Ta.Task&&Ta.Task.kill();Ta.util.mask.clear();var hash=this.mainId+'-'+this.subId;this.history.push(hash);Ta.hash.set(0,hash);fn=fn||this.hdl;var mainTitle=json.main.data[this.mainId],subTitle=subTT[this.mainId][this.subId]||'';enableHotClick&&Ta.util.sendHotClick('TAV2.MENU.'+mainTitle+(subTitle?'.'+subTitle:''));fn([this.mainId,this.subId],[mainTitle,subTitle]);};this.update=function(mod){create(mod||'sub');this.reload();};this.reload=function(){var arr=Ta.hash.get(0).split('-');this.change(arr[0],arr[1]);}
init();};Ta.Dialog=function(json,callback){var defaults={type:1,title:'温馨提示',hideCloseIcon:false,content:'',detail:'',tips:'',btnType:1,buttons:{text1:'',text2:''},winSize:1,extra:{top:'',left:'',width:'',zIndex:1001,heatmap:'',noPrompt:'',autoMask:true}};!json.extra&&(json.extra=defaults.extra);var opts=$.extend(true,defaults,json);var self=this;self.dialogId='';var create=function(){var extra=opts.extra;var zIndex=extra['zIndex'];while($('#fwin_dialog_fs_100'+zIndex)[0]){zIndex++;}
var message_id='fs_100'+zIndex;var dialogId='fwin_dialog_'+message_id;var contentId=dialogId+'_content';var closeIconId=dialogId+'_closeIcon';var tipsId=dialogId+'_tips';var btnId1=dialogId+'_btn1',btnId2=dialogId+'_btn2',btnContainer1=dialogId+'_btnCtn1';self.dialogId=dialogId;self.btnId1=btnId1;self.btnContainer1=btnContainer1;var dialogPosition=($.browser.msie&&$.browser.version<7)?'absolute':'fixed';extra['heatmap']&&(dialogPosition='absolute');var btnText1,btnText2,tips=opts.tips,btnType=opts.btnType;var typeList={1:['确 定','取消'],2:['是','否'],3:['确 定',''],4:['继 续',''],5:['','']};if(btnType!=6){btnType=typeList[btnType]?btnType:1;btnText1=typeList[btnType][0];btnText2=typeList[btnType][1];}else{btnText1=opts.buttons.text1;btnText2=opts.buttons.text2;}
var footerHtml='';if(tips||btnText1||btnText2){footerHtml=' <div class="float_footer"> ';footerHtml+='   <div class="frm_msg"> '
+'    <p id="'+tipsId+'" class="">'+tips+'</p> '
+'   </div> ';if(btnText1||btnText2){footerHtml+='  <div class="frm_btn"> ';btnText1&&function(){var rawHtml='<input type="button" id="'+btnId1+'"  value="'+btnText1+'"  class="btn_sbm"/> ';6==btnType?footerHtml+='<div  id="'+btnContainer1+'" style="position: relative;">'+rawHtml+'</div>':footerHtml+=rawHtml;}();btnText2&&(footerHtml+='   <input type="button" id="'+btnId2+'" value="'+btnText2+'"  class="btn_rst"/> ');footerHtml+='</div>';}
footerHtml+='</div>';}
var winSizeClass={1:'min',2:'mid'}[opts.winSize]||'min';var contentClass={1:'',2:'frm_cont',3:'confirm cf',4:'confirm cf',5:'confirm cf'}[opts.type]||'';var strHtml=' <div id="'+dialogId+'" style="position: '+dialogPosition+'; z-index: '+zIndex+'" class="float cf '+winSizeClass+'">'
+'  <div class="float_header"> '
+'   <h3><a id="'+closeIconId+'" href="javascript:void(0);" class="close">&times;</a>'+opts.title+'</h3>'
+'  </div>'
+'  <div class="float_cont cf"> '
+'   <div class="'+contentClass+'" id="'+contentId+'"> '
+'   </div> '
+'  </div> '
+footerHtml
+' </div> ';if(!$('#'+dialogId)[0]){$(strHtml).appendTo("body");}
var content=opts.content;var cssInfo={3:'success',4:'attent',5:'warn',6:'error'}[opts.type]||'';cssInfo&&(content=' <div class="'+cssInfo+'"> '
+'   <i class="i_confirmb"></i> '
+'   <h5>'+opts.content+'</h5> '
+'   <p>'+opts.detail+'</p> '
+'  </div> ');$('#'+contentId).html(content);$("#"+dialogId).show();var dialogWidth=extra['width']?parseInt(extra['width'])+'px':'auto';$('#'+contentId).css({"width":dialogWidth});dialogLeft=extra['left']||($(window).width()-$('#'+dialogId).width())/2;dialogTop=extra['top']||($(window).height()-$('#'+dialogId).height())/2;$("#"+dialogId).css({"top":dialogTop+"px","left":dialogLeft+"px"});if(!extra||typeof(extra['heatmap'])=='undefined'){$("#"+dialogId).draggable({handle:"h3.flb",drag:function(){if($("#frm_100_"+dialogId)){$("#frm_100_"+dialogId).css({"top":$("#"+dialogId).css("top"),"left":$("#"+dialogId).css("left")});}
if($("div[id^='calendar_']")){$("div[id^='calendar_']").css('display','none');}}});}
$('#'+btnId1).click(function(){buttonClick('btn1');});$('#'+btnId2).click(function(){buttonClick('btn2');});$('#'+closeIconId).click(function(){buttonClick('btnClose');});opts.hideCloseIcon&&$('#'+closeIconId).css('display','none');var noPrompt=(extra&&typeof(extra['noPrompt'])!='undefined')?extra['noPrompt']:false;if(noPrompt){$('#'+'promptOff').html('<input type="checkbox" id="noDataPromptOff" name="noDataPromptOff" value="1" style="position:relative;top:2px;"/> 不再提醒 ');}
opts.extra.autoMask&&Ta.Mask.create();var hidIframeId="frm_100_"+dialogId;if($("#"+hidIframeId)){$("#"+hidIframeId).remove();}
hidIframe="<iframe id=\""+hidIframeId+"\"></iframe>";$(hidIframe).appendTo("body");zIndex=parseInt(zIndex);zIndex--;$("#"+hidIframeId).css({"width":$("#"+dialogId).width(),"height":$("#"+dialogId).height(),"position":dialogPosition,"top":$("#"+dialogId).css("top"),"left":$("#"+dialogId).css("left"),"z-index":zIndex,"scrolling":"no","border":"0"});Ta.DialogManager.add(self.dialogId,self);},buttonClick=function(btnName){(btnName=='btn1'&&callback)?callback(self,self.dialogId,btnName):self.hideWindows();};this.hideWindows=function(){var dialogId=self.dialogId;$("#"+dialogId).hide();$("#"+dialogId).remove();$("#frm_100_"+dialogId).remove();if($("div[id^='calendar_']")){$("div[id^='calendar_']").css('display','none');}
opts.extra.autoMask&&Ta.Mask.destroy();Ta.DialogManager.remove(dialogId);return false;};this.closeWindows=this.hideWindows;this.showTips=function(msg){var tipsId=self.dialogId+'_tips';$("#"+tipsId).html(msg);},this.clearTips=function(){var tipsId=self.dialogId+'_tips';$("#"+tipsId).html('');}
create();return this;};Ta.Dialog.DIALOG_TYPE={COMMON:1,CONTROL:2,TEXT_INFO:3,TEXT_WARN:4,TEXT_WARN_RED:5,TEXT_ERROR:6};Ta.Dialog.BUTTON_TYPE={OK_CANCEL:1,YES_NO:2,OK:3,CONTINUE:4,NONE:5,CUSTOMIZE:6};Ta.Dialog.WIN_SIZE={MIN:1,MID:2};Ta.DialogManager=(function(){var _list=new Object();return{clearOtherDialog:null,add:function(id,dialog){!(id in _list)&&(_list[id]=dialog);},remove:function(id){if(id in _list){delete _list[id];}},clearAll:function(){for(var id in _list){(_list[id]instanceof Ta.Dialog)&&_list[id].closeWindows();}
_list=new Object();this.clearOtherDialog&&(this.clearOtherDialog(),this.clearOtherDialog=null);}}})();Ta.Login=(function(){var VERIFY_URL='http://ta.qq.com/verify';var _loginDialog=null,_maskDiv=null;var _isOpenLogin=false;var _dialogX,_dialogY,_dialogW=0,_dialogH=0;var _retUrl='';function setCenter(){if(!_isOpenLogin){return;}
var ww,wh,bgX,bgY;var dde=document.documentElement;if(top.innerWidth){ww=top.innerWidth;wh=top.innerHeight;bgX=top.pageXOffset;bgY=top.pageYOffset;}else{ww=dde.offsetWidth;wh=dde.offsetHeight;bgX=dde.scrollLeft;bgY=dde.scrollTop;}
_loginDialog.style.left=(bgX+(ww-_dialogW)/2)+'px';_loginDialog.style.top=(bgY+(wh-_dialogH)/3)+'px';Ta.Mask.create();setTimeout(setCenter,100);}
function createLoginDialog(){if(!_loginDialog){_loginDialog=document.createElement("div");}
var oS=_loginDialog.style;oS.display="block";oS.top="1px";oS.left="1px";oS.margin="0px";oS.padding="0px";oS.width="1px";oS.height="1px";oS.position="absolute";oS.zIndex="1000";_loginDialog.innerHTML='<iframe frameborder="no" scrolling="no" width="100%" height="100%" src="#"></iframe>';document.getElementsByTagName("body")[0].appendChild(_loginDialog);var url="http://ui.ptlogin2.qq.com/cgi-bin/login";url+="?qlogin_auto_login=0";url+="&style=0";url+="&appid=518011202&daid=75&s_url=";url+=encodeURIComponent(VERIFY_URL+'?ref='+encodeURIComponent(_retUrl)+'&rnd='+Math.random());_loginDialog.getElementsByTagName('iframe')[0].src=url;}
return{open:function(retUrl){if(_isOpenLogin){return;}
console.log('d');document.domain="qq.com";_retUrl=retUrl;_isOpenLogin=true;createLoginDialog();setCenter();},resize:function(w,h){if(_loginDialog){_loginDialog.style.visibility="hidden";_loginDialog.style.width=w+"px";_loginDialog.style.height=h+"px";_loginDialog.style.visibility="visible";_dialogW=w;_dialogH=h;setCenter();}},close:function(){if(_loginDialog){_isOpenLogin=false;_loginDialog.style.display="none";Ta.Mask.destroy();}}};})();window.ptlogin2_onClose=Ta.Login.close;window.ptlogin2_onResize=Ta.Login.resize;Ta.Mask=(function(){var _maskDiv='';var _isIE6=$.browser.msie&&$.browser.version<7;var _self=this;function resize(){_maskDiv.css({width:0,height:0}).css({width:width(),height:height()});}
function height(){var scrollHeight,offsetHeight;if(_isIE6){scrollHeight=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);offsetHeight=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight);if(scrollHeight<offsetHeight){return $(window).height()+'px';}else{return scrollHeight+'px';}}else{return $(document).height()+'px';}}
function width(){var scrollWidth,offsetWidth;if(_isIE6){scrollWidth=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth);offsetWidth=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth);if(scrollWidth<offsetWidth){return $(window).width()+'px';}else{return scrollWidth+'px';}}else{return $(document).width()+'px';}}
return{create:function(){if(_maskDiv&&_maskDiv.parent().length){return;}
$(window).bind('resize.overlay',resize);return(_maskDiv=(_maskDiv||$('<div></div>').css({height:'100%',left:0,position:'absolute',top:0,width:'100%',background:'#000','opacity':0.3,'z-index':777})).appendTo('body').css({width:width(),height:height()}));},destroy:function(){if(_maskDiv&&!_maskDiv.parent().length){return;}
$([document,window]).unbind('resize.overlay');_maskDiv.animate({opacity:'hide'},function(){$(this).remove().show();});}}})();Ta.Condition=function(options,fnc,fnt){var tools={'aToday':{id:'aToday',text:'今天'},'aYesterday':{id:'aYesterday',text:'昨天'},'aRecent7Days':{id:'aRecent7Days',text:'最近7天'},'aRecent30Days':{id:'aRecent30Days',text:'最近30天'},'cmpYesterDay':{id:'cmpYesterday',text:'与昨天对比'},'cmpLastWeekDate':{id:'cmpLastWeekDate',text:'与上周同天对比'},'cmpLastMonthDate':{id:'cmpLastMonthDate',text:'与上月同天对比'},'exportFile':{id:'exportFile',text:'导出数据',desc:'导出数据'},'aYesterdayLabel':{id:'aYesterdayLabel',text:'昨天',desc:'此时间您尚未开通腾讯分析'},'aRecent7DaysLabel':{id:'aRecent7DaysLabel',text:'最近7天',desc:'您开通腾讯分析还未满7天'},'aRecent30DaysLabel':{id:'aRecent30DaysLabel',text:'最近30天',desc:'您开通腾讯分析还未30天'},'aCustomDate':{id:'aCustomDate',text:'自定义时间',desc:''}},controls={0:{id:0,text:'展现粒度',name:'range',multiSelect:false,data:[{id:0,text:'按小时',value:'hour',desc:'按小时显示数据',checked:true},{id:1,text:'按天',value:'day',desc:'按天显示数据'},{id:2,text:'按周',value:'week',desc:'按周显示数据'},{id:3,text:'按月',value:'month',desc:'按月显示数据'}]},1:{id:1,text:'访客类型',name:'userType',multiSelect:false,data:[{id:2,text:'全部',value:'2',desc:'全部',checked:true},{id:0,text:'游客',value:'0',desc:'游客'},{id:1,text:'会员',value:'1',desc:'会员'}]},2:{id:2,multiSelect:false,name:'chartType',text:'图表类型',data:[{id:0,text:'area',value:'area',checked:true},{id:1,text:'spline',value:'spline'},{id:2,text:'line',value:'line'}]},3:{id:3,text:''}},conf={seperate:options.seperate||'_'},selectList=[];var create=function(){var arrGrps=[];var arr=[];var tls=options.toolbar;for(var i in tls.data){arr=[];for(var j in tls.data[i]){var btn=$.extend({},tools[tls.data[i][j].id],tls.data[i][j]);if(btn.id!='aCustomDate'&&btn.id.indexOf('Label')==-1){cla=btn.checked?'active':'';arr.push('<li class="'+cla+'"><a href="javascript:void(0);" id="'+btn.id+'">'+btn.text+'</a></li>');}}
arrGrps.push(arr.join(''));}
$('#'+tls.container).html(arrGrps.join(''));var arrCtrls=[];var ctrls=options.controls;ctrls.data=ctrls.data||[];if(options.items&&options.items.data&&options.items.data.length>0){var multiSelect=options.items.hasOwnProperty('multiSelect')?options.items.multiSelect:false;ctrls.data.unshift({id:'item',name:'item',text:'指标类型',multiSelect:multiSelect,data:options.items.data});}
var tableItems=options.tableItems;if(tableItems&&tableItems.data&&tableItems.data.length>0){if(tableItems.container==ctrls.container)
{var multiSelect=tableItems.hasOwnProperty('multiSelect')?tableItems.multiSelect:false;var id=multiSelect?'tableItem':'tableItem';ctrls.data.unshift({id:id,name:id,text:'指标类型',multiSelect:multiSelect,data:tableItems.data});$('#'+tableItems.topContainer).empty();}else{var arr=[];for(var i in tableItems.data){var item=tableItems.data[i];arr.push('<li><label><input type="checkbox" id="'+item.id+'" value="'+item.id+'" title="'+item.desc+'" tag="'+item.text+'" name="tableItem[]"'+(item.checked?' checked="true" ':'')+'/>'+item.text+'</label></li>');}
$('#'+tableItems.container).html(arr.join(''));$('#'+tableItems.container).find('input').click(function(){Ta.util.pageHotClick($(this).attr('tag'));fnt&&fnt(this);});}}else{$('#'+tableItems.topContainer).empty();$('#'+tableItems.topContainer).hide();}
if(ctrls.data&&ctrls.data.length>0){for(var i in ctrls.data){arr=[];var oldCtrl=ctrls.data[i];var ctrl=controls[ctrls.data[i].id];if(ctrl){var arrItem=[];ctrl.multiSelect=oldCtrl.multiSelect;if(oldCtrl.data&&oldCtrl.data.length>0){for(var j in ctrl.data){var cItem=ctrl.data[j];for(var k in oldCtrl.data){if(cItem.id==oldCtrl.data[k].id){oldItem=oldCtrl.data[k];cItem.checked=oldItem.hasOwnProperty('checked')?oldItem.checked:cItem.checked;arrItem.push(cItem);break;}}}
ctrl.data=arrItem;}}
else{ctrl=oldCtrl;}
if(ctrl.data.length==0){continue;};var ctrlType=ctrl.multiSelect?'checkbox':'radio';var hasNoDefaultValue=true;for(var i in ctrl.data){if(ctrl.data[i].checked){hasNoDefaultValue=false};}
if(hasNoDefaultValue){ctrl.data[0].checked=true};for(var j in ctrl.data){var cItem=ctrl.data[j];var id=ctrl.name+conf.seperate+(cItem.id||cItem.value);var value=cItem.value||cItem.id;var checked=cItem.checked;var strDesc=cItem.desc?' title="'+cItem.desc+'" ':'';arr.push('<label for="'+id+'" id="lab_'+id+'" '+strDesc+'>'
+'<input type="'+ctrlType+'" '+strDesc+' id="'+id+'" name="'+ctrl.name+'" value="'+value
+'" tag="'+cItem.text+'"'+(checked?' checked="true" ':'')+' />'+cItem.text+'</label>');if(ctrl.name=='item'&&checked){selectList.push(id);}}
arrCtrls.push('<dt>'+ctrl.text+'：</dt><dd id="dd_'+ctrl.name+'">'+arr.join('')+'</dd>');}
$('#'+ctrls.container).html(arrCtrls.join(''));$('#'+ctrls.container).find('input').click(function(){if($(this).attr('name')=='item'&&$(this).attr('type')=='checkbox'){var newId=$(this).attr('id');if($(this).checked){selectList.push(newId);if(selectList.length>3){var id=selectList.shift();$('#'+id).attr('checked',false);}}else{for(var id in selectList){if(id==newId){delete(id);}}}}
Ta.util.pageHotClick($(this).attr('tag'));fnc&&fnc(this);});}
else{$('#'+ctrls.container).empty();$('#'+ctrls.buttonId).hide();}};this.getResult=function(type){var arr=[];var ctrls=options.controls;var hasTableItem=(type=='table'&&options.tableItems!=null);$('#'+ctrls.container).find('input:checked').each(function(){if(!hasTableItem||$(this).attr('name')!='item'){var name=$(this).attr('name')+($(this).attr('type')=='checkbox'?'[]':'');arr.push(name+'='+$(this).val());}});var lstItems=options.tableItems;if(hasTableItem&&lstItems.container!=ctrls.container){$('#'+lstItems.container).find('input:checked').each(function(){arr.push($(this).attr('name')+'='+$(this).val());});}
return arr.join('&');};create();};Ta.Formatter=(function(){return{numberFormat:function(val,dec){dec=dec||0;return Highcharts.numberFormat(val,dec);},truncate:function(val,len){return(len&&val.length>len)?val.substr(0,len)+'...':val;}}})();/*  |xGv00|9a7e028a2f19023f6a8f073e6c372809 */